# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    ## you may remove this if you don't use vgo
    #- go mod download
    ## you may remove this if you don't need go generate
    #- go generate ./...
builds:
- env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  - windows
  - freebsd
  goarch:
  - amd64
  asmflags:
  - all=-trimpath={{.Env.GOPATH}}
  ldflags:
  - all=-trimpath={{.Env.GOPATH}}
  - -s -w -X github.com/davidcv5/kongup/cmd.VERSION={{ .Tag }} -X github.com/davidcv5/kongup/cmd.COMMIT={{ .ShortCommit }}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
nfpm:
  name_template: '{{ .ProjectName }}_{{ .Tag }}_{{ .Arch }}'
  homepage:  https://github.com/davidcv5/kongup
  description: Declarative configuration for Kong
  maintainer: David Cruz <davidcv5@gmail.com>
  license: Apache License v2.0
  formats:
  - deb
  - rpm
